#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
  path:     /
  controller: App\Controller\DefaultController::homepage

task_list:
  path:     /tasks
  controller: App\Controller\TaskController::listTasks
  